# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaxAppeal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaxAppeal
  pod 'CBFlashyTabBarController'
  pod 'Shuffle-iOS'
  target 'TaxAppealTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaxAppealUITests' do
    # Pods for testing
  end

end
